# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RT-Client-Console
version:      0.1.0
version_from: lib/RT/Client/Console.pm
installdirs:  site
requires:
    Config::Tiny:                  2.03
    Curses:                        1.13
    Curses::Forms:                 1.997
    Curses::Widgets:               1.997
    Error:                         0.17008
    List::MoreUtils:               0.21
    Params::Validate:              0.88
    parent:                        0.218
    POE:                           0.9989
    relative:                      0.03
    RT::Client::REST:              0.34
    Test::More:                    0
    version:                       0.7203

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
